[build.environment]
DART_SASS_VERSION = "1.89.2"
GO_VERSION = "1.24.1"
HUGO_VERSION = "0.147.8"
NODE_VERSION = "18.19.1"
TZ = "Asia/Makassar"

[build]
publish = "public"
command = """\
  curl -sLJO "https://github.com/sass/dart-sass/releases/download/${DART_SASS_VERSION}/dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  tar -C "${HOME}/.local" -xf "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  rm "dart-sass-${DART_SASS_VERSION}-linux-x64.tar.gz" && \
  export PATH="${HOME}/.local/dart-sass:${PATH}" && \
  git config core.quotepath false && \
  hugo --gc --minify --baseURL "${URL}"
  """
